using BobCrm.Api.Base;
using BobCrm.Api.Base.Models;
using BobCrm.Api.Services;
using FluentAssertions;
using System.Text.Json;
using Xunit;

namespace BobCrm.Api.Tests;

/// <summary>
/// DefaultTemplateGenerator 默认模板生成器测试
/// </summary>
public class DefaultTemplateGeneratorTests
{
    private static DefaultTemplateGenerator CreateGenerator()
    {
        return new DefaultTemplateGenerator();
    }

    private static EntityDefinition CreateTestEntity(List<FieldMetadata>? fields = null)
    {
        return new EntityDefinition
        {
            EntityName = "Customer",
            EntityRoute = "customer",
            FullTypeName = "BobCrm.Customer",
            Namespace = "BobCrm",
            Status = EntityStatus.Published,
            Fields = fields ?? new List<FieldMetadata>
            {
                new FieldMetadata
                {
                    PropertyName = "code",
                    DataType = FieldDataType.String,
                    DisplayName = new Dictionary<string, string?> { ["zh"] = "编码" },
                    IsRequired = true,
                    SortOrder = 1
                },
                new FieldMetadata
                {
                    PropertyName = "name",
                    DataType = FieldDataType.String,
                    DisplayName = new Dictionary<string, string?> { ["zh"] = "名称" },
                    IsRequired = true,
                    SortOrder = 2
                }
            }
        };
    }

    #region GenerateAsync Basic Tests

    [Fact]
    public async Task GenerateAsync_ShouldReturnFormTemplate()
    {
        // Arrange
        var generator = CreateGenerator();
        var entity = CreateTestEntity();

        // Act
        var result = await generator.GenerateAsync(entity);

        // Assert
        result.Should().NotBeNull();
        result.Should().BeOfType<FormTemplate>();
    }

    [Fact]
    public async Task GenerateAsync_ShouldSetCorrectEntityType()
    {
        // Arrange
        var generator = CreateGenerator();
        var entity = CreateTestEntity();

        // Act
        var result = await generator.GenerateAsync(entity);

        // Assert
        result.EntityType.Should().Be("customer");
    }

    [Fact]
    public async Task GenerateAsync_ShouldSetSystemDefault()
    {
        // Arrange
        var generator = CreateGenerator();
        var entity = CreateTestEntity();

        // Act
        var result = await generator.GenerateAsync(entity);

        // Assert
        result.IsSystemDefault.Should().BeTrue();
        result.UserId.Should().Be("__system__");
    }

    [Fact]
    public async Task GenerateAsync_ShouldIncludeAutoGeneratedTag()
    {
        // Arrange
        var generator = CreateGenerator();
        var entity = CreateTestEntity();

        // Act
        var result = await generator.GenerateAsync(entity);

        // Assert
        result.Tags.Should().Contain("auto-generated");
    }

    #endregion

    #region ViewState Tests

    [Fact]
    public async Task GenerateAsync_WithDetailViewState_ShouldSetDetailUsageType()
    {
        // Arrange
        var generator = CreateGenerator();
        var entity = CreateTestEntity();

        // Act
        var result = await generator.GenerateAsync(entity, "DetailView");

        // Assert
        result.UsageType.Should().Be(FormTemplateUsageType.Detail);
    }

    [Fact]
    public async Task GenerateAsync_WithListViewState_ShouldSetListUsageType()
    {
        // Arrange
        var generator = CreateGenerator();
        var entity = CreateTestEntity();

        // Act
        var result = await generator.GenerateAsync(entity, "List");

        // Assert
        result.UsageType.Should().Be(FormTemplateUsageType.List);
    }

    [Fact]
    public async Task GenerateAsync_WithDetailEditViewState_ShouldSetEditUsageType()
    {
        // Arrange
        var generator = CreateGenerator();
        var entity = CreateTestEntity();

        // Act
        var result = await generator.GenerateAsync(entity, "DetailEdit");

        // Assert
        result.UsageType.Should().Be(FormTemplateUsageType.Edit);
    }

    [Fact]
    public async Task GenerateAsync_WithCreateViewState_ShouldSetCombinedUsageType()
    {
        // Arrange
        var generator = CreateGenerator();
        var entity = CreateTestEntity();

        // Act
        var result = await generator.GenerateAsync(entity, "Create");

        // Assert
        result.UsageType.Should().Be(FormTemplateUsageType.Combined);
    }

    #endregion

    #region LayoutJson Tests

    [Fact]
    public async Task GenerateAsync_ShouldGenerateValidJson()
    {
        // Arrange
        var generator = CreateGenerator();
        var entity = CreateTestEntity();

        // Act
        var result = await generator.GenerateAsync(entity);

        // Assert
        result.LayoutJson.Should().NotBeNullOrEmpty();
        var action = () => JsonDocument.Parse(result.LayoutJson!);
        action.Should().NotThrow();
    }

    [Fact]
    public async Task GenerateAsync_ForList_ShouldIncludeDataGrid()
    {
        // Arrange
        var generator = CreateGenerator();
        var entity = CreateTestEntity();

        // Act
        var result = await generator.GenerateAsync(entity, "List");

        // Assert
        result.LayoutJson.Should().Contain("datagrid");
    }

    [Fact]
    public async Task GenerateAsync_ForDetailEdit_ShouldIncludeButtons()
    {
        // Arrange
        var generator = CreateGenerator();
        var entity = CreateTestEntity();

        // Act
        var result = await generator.GenerateAsync(entity, "DetailEdit");

        // Assert
        result.LayoutJson.Should().Contain("button");
        result.LayoutJson.Should().Contain("BTN_SAVE");
    }

    #endregion

    #region Field Handling Tests

    [Fact]
    public async Task GenerateAsync_ShouldMapStringFieldToTextWidget()
    {
        // Arrange
        var generator = CreateGenerator();
        var entity = CreateTestEntity();

        // Act
        var result = await generator.GenerateAsync(entity, "DetailView");

        // Assert
        result.LayoutJson.Should().Contain("text");
    }

    [Fact]
    public async Task GenerateAsync_ShouldIncludeFieldDataField()
    {
        // Arrange
        var generator = CreateGenerator();
        var entity = CreateTestEntity();

        // Act
        var result = await generator.GenerateAsync(entity, "DetailView");

        // Assert
        result.LayoutJson.Should().Contain("code");
        result.LayoutJson.Should().Contain("name");
    }

    [Fact]
    public async Task GenerateAsync_WithBooleanField_ShouldMapToCheckbox()
    {
        // Arrange
        var generator = CreateGenerator();
        var entity = CreateTestEntity(new List<FieldMetadata>
        {
            new FieldMetadata
            {
                PropertyName = "isActive",
                DataType = FieldDataType.Boolean,
                DisplayName = new Dictionary<string, string?> { ["zh"] = "是否激活" }
            }
        });

        // Act
        var result = await generator.GenerateAsync(entity, "DetailView");

        // Assert
        result.LayoutJson.Should().Contain("checkbox");
    }

    [Fact]
    public async Task GenerateAsync_WithNumberField_ShouldMapToNumber()
    {
        // Arrange
        var generator = CreateGenerator();
        var entity = CreateTestEntity(new List<FieldMetadata>
        {
            new FieldMetadata
            {
                PropertyName = "quantity",
                DataType = FieldDataType.Int32,
                DisplayName = new Dictionary<string, string?> { ["zh"] = "数量" }
            }
        });

        // Act
        var result = await generator.GenerateAsync(entity, "DetailView");

        // Assert
        result.LayoutJson.Should().Contain("number");
    }

    [Fact]
    public async Task GenerateAsync_WithDateTimeField_ShouldMapToDate()
    {
        // Arrange
        var generator = CreateGenerator();
        var entity = CreateTestEntity(new List<FieldMetadata>
        {
            new FieldMetadata
            {
                PropertyName = "createdAt",
                DataType = FieldDataType.DateTime,
                DisplayName = new Dictionary<string, string?> { ["zh"] = "创建时间" }
            }
        });

        // Act
        var result = await generator.GenerateAsync(entity, "DetailView");

        // Assert
        result.LayoutJson.Should().Contain("date");
    }

    [Fact]
    public async Task GenerateAsync_WithEnumField_ShouldMapToEnumSelector()
    {
        // Arrange
        var generator = CreateGenerator();
        var entity = CreateTestEntity(new List<FieldMetadata>
        {
            new FieldMetadata
            {
                PropertyName = "status",
                DataType = FieldDataType.Enum,
                EnumDefinitionId = Guid.NewGuid(),
                DisplayName = new Dictionary<string, string?> { ["zh"] = "状态" }
            }
        });

        // Act
        var result = await generator.GenerateAsync(entity, "DetailView");

        // Assert
        result.LayoutJson.Should().Contain("enumselector");
    }

    [Fact]
    public async Task GenerateAsync_WithLongTextField_ShouldMapToTextarea()
    {
        // Arrange
        var generator = CreateGenerator();
        var entity = CreateTestEntity(new List<FieldMetadata>
        {
            new FieldMetadata
            {
                PropertyName = "description",
                DataType = FieldDataType.String,
                Length = 1000,
                DisplayName = new Dictionary<string, string?> { ["zh"] = "描述" }
            }
        });

        // Act
        var result = await generator.GenerateAsync(entity, "DetailView");

        // Assert
        result.LayoutJson.Should().Contain("textarea");
    }

    #endregion

    #region Validation Tests

    [Fact]
    public async Task GenerateAsync_WithNullEntity_ShouldThrow()
    {
        // Arrange
        var generator = CreateGenerator();

        // Act & Assert
        await Assert.ThrowsAsync<ArgumentNullException>(() =>
            generator.GenerateAsync(null!));
    }

    [Fact]
    public async Task GenerateAsync_WithEmptyFields_ShouldUseFallbackFields()
    {
        // Arrange
        var generator = CreateGenerator();
        var entity = CreateTestEntity(new List<FieldMetadata>());

        // Act
        var result = await generator.GenerateAsync(entity);

        // Assert
        // Should have fallback code and name fields
        result.LayoutJson.Should().Contain("code");
        result.LayoutJson.Should().Contain("name");
    }

    #endregion

    #region Template Name Tests

    [Fact]
    public async Task GenerateAsync_ShouldGenerateCorrectTemplateName()
    {
        // Arrange
        var generator = CreateGenerator();
        var entity = CreateTestEntity();

        // Act
        var result = await generator.GenerateAsync(entity, "DetailView");

        // Assert
        result.Name.Should().Contain("TEMPLATE_NAME_");
        result.Name.Should().Contain("CUSTOMER");
        result.Name.Should().Contain("DETAILVIEW");
    }

    [Fact]
    public async Task GenerateAsync_ForList_ShouldGenerateListTemplateName()
    {
        // Arrange
        var generator = CreateGenerator();
        var entity = CreateTestEntity();

        // Act
        var result = await generator.GenerateAsync(entity, "List");

        // Assert
        result.Name.Should().Contain("LIST");
    }

    #endregion

    #region Special Entity Tests

    [Fact]
    public async Task GenerateAsync_ForUsersEntity_ShouldIncludeUserRoleWidget()
    {
        // Arrange
        var generator = CreateGenerator();
        var entity = CreateTestEntity();
        entity.EntityRoute = "users";

        // Act
        var result = await generator.GenerateAsync(entity, "DetailView");

        // Assert
        result.LayoutJson.Should().Contain("userrole");
    }

    [Fact]
    public async Task GenerateAsync_ForRolesEntity_ShouldIncludePermTreeWidget()
    {
        // Arrange
        var generator = CreateGenerator();
        var entity = CreateTestEntity();
        entity.EntityRoute = "roles";

        // Act
        var result = await generator.GenerateAsync(entity, "DetailView");

        // Assert
        result.LayoutJson.Should().Contain("permtree");
    }

    #endregion

    #region DeletedField Handling Tests

    [Fact]
    public async Task GenerateAsync_ShouldExcludeDeletedFields()
    {
        // Arrange
        var generator = CreateGenerator();
        var entity = CreateTestEntity(new List<FieldMetadata>
        {
            new FieldMetadata
            {
                PropertyName = "activeField",
                DataType = FieldDataType.String,
                IsDeleted = false,
                DisplayName = new Dictionary<string, string?> { ["zh"] = "活动字段" }
            },
            new FieldMetadata
            {
                PropertyName = "deletedField",
                DataType = FieldDataType.String,
                IsDeleted = true,
                DisplayName = new Dictionary<string, string?> { ["zh"] = "删除字段" }
            }
        });

        // Act
        var result = await generator.GenerateAsync(entity, "DetailView");

        // Assert
        result.LayoutJson.Should().Contain("activeField");
        result.LayoutJson.Should().NotContain("deletedField");
    }

    #endregion
}
